# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - main: ./cmd/graft
    binary: graft
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - # This template ensures your folders look like: Graft_1.0.5_linux_amd64
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ title .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: [zip]


checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ .Tag }}-next"

release:
  header: |
    ## Feature Update with Graft  🚀
    
    ### V2.2 Highlights:
    1. **Rollback Feature**: Added rollback functionality to revert to previous deployments.
    2. **Bug Fixes and Improvements**: 
                        - Webhook detection and error handling.   
                        - graft-compose.yml optimizations. 
    
    ### V2 Highlights:
    This release introduces significant enhancements to Graft, moving from basic local-to-server deployments to a more robust CI/CD-driven workflow using GitHub Actions and our new `graft-hook` service.
    
    1. **Git Remote Modes**: Move away from direct local-to-server channels. Deployments now go through GitHub Workflows and CI/CD channels.
    2. **Graft-Hook**: A new webhook service personalized specifically for Graft-based servers, maintaining a zero-config solution with proper security.
    3. **Automated GitHub Workflows**: Graft now generates production-ready workflows automatically from your `graft-compose.yml` context.
    4. **Enhanced Monitoring**: Easy CLI-based monitoring for `graft-hook`, including real-time build error logs.
    5. **Cloudflare API Integration**: Automated DNS zone mapping based on Traefik host labels.
    6. **Cloudflare Zone Registry**: Manage multiple Cloudflare accounts and zones with an interactive selection menu.
    7. **Database Backup Automation(Infrastructure)**: Easily backup Infrastructure databases to S3/R2(Experimental).
  
  footer: |
    ---
    Released by **skssmd** using [GoReleaser](https://github.com/goreleaser/goreleaser).