# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - main: ./cmd/graft
    binary: graft
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ title .Os }}_{{ .Arch }}"
    format: zip

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ .Tag }}-next"

# Winget configuration
winget:
  - name: Graft
    publisher: skssmd
    license: MIT
    copyright: Copyright (c) 2025 skssmd
    homepage: https://github.com/skssmd/Graft
    short_description: A high-performance, zero-overhead deployment engine that extends the Docker Compose workflow to cloud infrastructure via SSH
    description: |
      A high-performance, zero-overhead deployment engine that extends the Docker Compose workflow 
      to cloud infrastructure via SSH. Graft enables native remote management of AWS, GCP, and VPS 
      instances with no agent installs or server-side overhead required. With V2.0 Graft is now 
      optimized for git and github actions ci/cd flow
    
    tags:
      - graft
      - Graft
      - deployment
      - devops
      - dev ops
      - easy deployment
      - docker compose
      - docker
      - ssh
      - hosting
      - cloud
    
    publisher_url: https://github.com/skssmd
    publisher_support_url: https://github.com/skssmd/Graft/issues
    license_url: https://github.com/skssmd/Graft/blob/main/LICENSE
    copyright_url: https://github.com/skssmd/Graft/blob/main/LICENSE
    release_notes_url: https://github.com/skssmd/Graft/releases/tag/v{{.Version}}
    
    author: skssmd
    
    # Installation notes
    release_notes: |
      - Cloudflare API Integration: Automated DNS zone mapping based on Traefik host labels.
      - Cloudflare Zone Registry: Manage multiple Cloudflare accounts and zones with an interactive selection menu.
      - Database Backup Automation: Easily backup infrastructure databases to S3/R2 (Experimental).
      - Rollback to versions: Easily rollback and revert changes to previous deployments.
      - Optimized for Git and GitHub Actions CI/CD flows.
      - Improved domain detection.
      - Duplicate record handling.
      - Ghcr image linking.
      - Boilerplate service priority guidelines.
      - Webhook detection and error handling.
    
    # Repository configuration
    repository:
      owner: skssmd                    # ← CHANGED: Your fork, not microsoft
      name: winget-pkgs
      branch: "{{.ProjectName}}-{{.Version}}-{{.ShortCommit}}"
      token: "{{ .Env.WINGET_GITHUB_TOKEN }}"
      pull_request:
        enabled: true
        draft: false
        base:
          owner: microsoft             # ← PR still targets microsoft
          name: winget-pkgs
          branch: master
    
    commit_author:
      name: skssmd
      email: skssmd78475@gmail.com
    
    commit_msg_template: "New version: {{ .PackageIdentifier }} version {{ .Tag }}"
    
    # Skip upload for testing
    skip_upload: false
release:
  draft: false
  prerelease: auto
  
  header: |
    winget install skssmd.Graft
    ```
    
    **Or upgrade:**
    ```powershell
    winget upgrade skssmd.Graft
    
  
  footer: |
    ---
    Released by **skssmd** using [GoReleaser](https://github.com/goreleaser/goreleaser)