name: Deploy

on:
  workflow_run:
    workflows: ["CI/CD Pipeline"]
    types:
      - completed
  release:
    types: [published]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy via Webhook
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    environment: CI CD
    
    steps:
      - name: Send Webhook Request
        run: |
          curl -X POST https://graft-hook.docusup.com/webhook \
            -H "Content-Type: application/json" \
            -d '{
              "project": "onehr",
              "repository": "${{ github.event.repository.name }}",
              "token": "${{ secrets.GITHUB_TOKEN }}",
              "user": "${{ github.actor }}",
              "type": "image",
              "registry": "ghcr.io"
            }'
